```{r}
rm(list = ls())
```


```{r}
library(openxlsx)
library(tidyverse)
library(ggpubr)
library(ggforce)
library(reshape2)
library(ggpubr)
library(org.Mm.eg.db)
library(AnnotationDbi)
library(enrichplot)
library(clusterProfiler)
library(msigdbr)
library(forcats)
library(ggrepel)
library(GSVA)
library(SingleCellExperiment)
library(scran)
```

```{r}
fit <- readRDS("/vol/ExtraVol/ParasiteDEX/parasite_glmGamPoi_fit_pseudobulked.RDS")
cnt <- fit[["data"]]@assays@data@listData[["counts"]]
sce <- SingleCellExperiment(assays = list(counts = cnt))
sce <- computeSumFactors(sce)
sce <- logNormCounts(sce)
normalized_counts <- logcounts(sce)

#Read the genomic feature table
genomic_features <- read.csv("/vol/ExtraVol/Genomic_Features.tsv", row.names = NULL, sep="\t")
genomic_features_unique <- genomic_features %>%
  dplyr::select(c(Symbol, Name)) %>%
  dplyr::distinct()
protein_coding_genes <- unique(subset(genomic_features, Gene.Type == "protein-coding")$Symbol)

normalized_counts <- subset(normalized_counts, rownames(normalized_counts) %in% protein_coding_genes)

#This is to add full names of the genes to the results
gene_metadata <- dplyr::select(genomic_features, c(Name, Symbol)) %>% 
  dplyr::rename("name" = "Symbol",
                "open_name" = "Name") %>%
  distinct()

entrezid_mapper <- AnnotationDbi::select(org.Mm.eg.db, keys=keys(org.Mm.eg.db), columns = c("SYMBOL", "ENTREZID")) %>% dplyr::rename("Symbol" = "SYMBOL")

normalized_counts_temp <- as.data.frame(normalized_counts) %>%
  dplyr::mutate(Symbol = rownames(normalized_counts))
normalized_counts_withENTREZID <- merge(normalized_counts_temp, entrezid_mapper, by="Symbol")
rownames(normalized_counts_withENTREZID) <- normalized_counts_withENTREZID$ENTREZID
normalized_counts_withENTREZID <- dplyr::select(normalized_counts_withENTREZID, -c(ENTREZID, Symbol))
rm(normalized_counts_temp)

infection_results_temp <- read.xlsx("/vol/ExtraVol/ParasiteDEX/DEX_results_parasite_infection_pseudobulked.xlsx")
infection_results_temp <- infection_results_temp %>% dplyr::rename("Symbol" = "name")
infection_results_temp <- subset(infection_results_temp, !grepl("^Rps|^Rpl", Symbol))
infection_results <- merge(infection_results_temp, entrezid_mapper, by="Symbol") %>%
  dplyr::arrange(desc(f_statistic))
top_infection_genes <- head(infection_results, n=nrow(infection_results)/100)$ENTREZID

# Define the path to the Excel file
file_infection_stage_dex <- "/vol/ExtraVol/ParasiteDEX/ParasiteDEX_OverallStageGenes_Pseudobulked.xlsx"

# Read each sheet into a corresponding data frame
early_infection_results_temp <- read.xlsx(file_infection_stage_dex, sheet = "early")
early_infection_results <- merge(early_infection_results_temp, entrezid_mapper, by="Symbol") %>%
  dplyr::arrange(desc(signed_adj_pval))

peak_infection_results_temp <- read.xlsx(file_infection_stage_dex, sheet = "peak")
peak_infection_results <- merge(peak_infection_results_temp, entrezid_mapper, by="Symbol") %>%
  dplyr::arrange(desc(signed_adj_pval))

repair_infection_results_temp <- read.xlsx(file_infection_stage_dex, sheet = "repair")
repair_infection_results <- merge(repair_infection_results_temp, entrezid_mapper, by="Symbol") %>%
  dplyr::arrange(desc(signed_adj_pval))
# interaction_results_temp <- read.xlsx("/vol/ExtraVol/ParasiteDEX/DEX_results_parasite_interaction_pseudobulked.xlsx")
# interaction_results_temp <- subset(interaction_results_temp, !grepl("^Rps|^Rpl", Symbol))
# interaction_results <- merge(interaction_results_temp, entrezid_mapper, by="Symbol") %>%
#   dplyr::arrange(desc(f_statistic)) %>% 
#   mutate(rank = seq(from = (n() - 1) / 2, to = -(n() - 1) / 2, by = -1))
# top_interaction_genes <- head(interaction_results, n=nrow(interaction_results)/100)$ENTREZID

reactome <- msigdbr(species = "Mus musculus", category = "C2", subcategory = "CP:REACTOME") %>% dplyr::select(gs_name, entrez_gene)
gobp <- msigdbr(species = "Mus musculus", category = "C5", subcategory = "GO:BP") %>% dplyr::select(gs_name, entrez_gene)
```

```{r}
enrichment_gobp_infection <- enricher(top_infection_genes, 
                            TERM2GENE = gobp, 
                            pvalueCutoff=0.01,
                            universe = infection_results$ENTREZID)
enrichment_gobp_infection <- setReadable(enrichment_gobp_infection, 'org.Mm.eg.db', "ENTREZID")
```

```{r}
enrichment_reactome_infection <- enricher(top_infection_genes, 
                                TERM2GENE = reactome,
                                pvalueCutoff=0.01,
                                universe = infection_results$ENTREZID)
enrichment_reactome_infection <- setReadable(enrichment_reactome_infection, 'org.Mm.eg.db', "ENTREZID")
```

```{r}
peak_infection_genes_ranked<-peak_infection_results$signed_adj_pval
names(peak_infection_genes_ranked)<-peak_infection_results$ENTREZID

peak_infection_GSEAobject <- GSEA(peak_infection_genes_ranked, 
                             TERM2GENE = reactome,
                             eps = 0)

peak_infection_GSEAobject <- setReadable(peak_infection_GSEAobject, 'org.Mm.eg.db', 'ENTREZID')
peak_infection_GSEAlist <- peak_infection_GSEAobject@result %>%
  dplyr::mutate(signed_padj = sign(NES)*-log10(p.adjust)) %>%
  dplyr::arrange(desc(signed_padj))
```

```{r}
reactome_genesets_subset <- reactome %>% 
  subset(gs_name %in% c("REACTOME_DEGRADATION_OF_THE_EXTRACELLULAR_MATRIX",
                        "REACTOME_COLLAGEN_FORMATION",
                        "REACTOME_CELLULAR_RESPONSE_TO_HEAT_STRESS",
                      "REACTOME_ANTIGEN_PROCESSING_CROSS_PRESENTATION"))

reactome_list <- unlist(split(reactome_genesets_subset, 
                              f = reactome_genesets_subset$gs_name), 
                        recursive = F)
```

```{r}
gsva_object <- gsvaParam(exprData = as.matrix(normalized_counts_withENTREZID), geneSets = reactome_list)
gsva_res_reactome <- gsva(gsva_object, verbose=TRUE)
```

### GSVA PLOTS ###

```{r}
# Function to assign shorter group names based on keywords
short_group_name <- function(x) {
  case_when(
    str_detect(x, "uninfected") ~ "uninfected",
    str_detect(x, "early") ~ "early",
    str_detect(x, "peak") ~ "peak",
    str_detect(x, "repair") ~ "repair",
    TRUE ~ "other"
  )
}

gsva_res_reactome_melted <- reshape2::melt(gsva_res_reactome, 
                                           varnames=c('GeneSet', 'SampleName'),
                                           value.name = "GSVAscore") %>%
  dplyr::mutate(SampleGroup = str_remove_all(SampleName, '_Rep.+'),
                GeneSet = str_remove_all(GeneSet, ".entrez_gene"),
                GeneSet = str_remove_all(GeneSet, "REACTOME_"),
                PlotGroup = short_group_name(SampleGroup),
                identity_simplified = str_extract(SampleGroup, "^[^_]+"))

# Function to create an ordering factor
ordering_factor <- function(x) {
  case_when(
    str_detect(x, "uninfected") ~ "1_uninfected",
    str_detect(x, "early") ~ "2_early",
    str_detect(x, "peak") ~ "3_peak",
    str_detect(x, "repair") ~ "4_repair",
    TRUE ~ "5_other"
  )
}

# Add the ordering factor to the dataframe
gsva_res_reactome_melted <- gsva_res_reactome_melted %>%
  mutate(OrderFactor = ordering_factor(SampleGroup),
         SampleGroup = factor(SampleGroup, levels = unique(SampleGroup[order(OrderFactor)])))

# Optionally, you can remove the OrderFactor column if it's no longer needed
gsva_res_reactome_melted <- dplyr::select(gsva_res_reactome_melted, -OrderFactor)

# Define group colors
group_colors <- c(
  "uninfected" = "#6baed6",  # Darker Pastel Blue
  "early" = "#fd8d3c",       # Darker Pastel Orange
  "peak" = "#fb6a4a",        # Darker Pastel Red
  "repair" = "#74c476"       # Darker Pastel Green
)
```

```{r}
plotdata <- subset(gsva_res_reactome_melted, GeneSet == "ANTIGEN_PROCESSING_CROSS_PRESENTATION")
plotdata$PlotGroup <- factor(plotdata$PlotGroup, levels = c("uninfected",
                                                            "early",
                                                            "peak",
                                                            "repair"))
# Calculate the median GSVAscore for each PlotGroup and identity_simplified
median_data <- plotdata %>%
  group_by(identity_simplified, PlotGroup) %>%
  summarize(median_GSVAscore = median(GSVAscore, na.rm = TRUE), .groups = 'drop')

pdf("/vol/ExtraVol/ParasiteDEX/GSEA/GSVA_AntigenProcessing.pdf", width = 2, height = 6)
ggplot(plotdata, aes(y = GSVAscore, x = PlotGroup, color = PlotGroup)) +
  geom_point() +
  geom_line(data = median_data, aes(y = median_GSVAscore, group = 1), color = "black") +
  scale_color_manual(values = group_colors) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 5),
        strip.text = element_text(size = 4),
        axis.title.x = element_blank()) +
  facet_wrap(~identity_simplified, ncol = 2, nrow=5)+
  guides(color = "none")  # Remove the legend
dev.off()
```

```{r}
ggplot(gsva_res_reactome_melted, aes(y=GSVAscore, x=SampleGroup))+
  geom_point()+
  theme_minimal()+
  ggtitle(paste0(unique(gsva_res_reactome_melted$GeneSet)))
  
```

