```{r}
rm(list = ls())
```

```{r}
library(loupeR)
library(Seurat)
library(tidyverse)
library(data.table)
library(Matrix)
```

```{r}
cnt <- as.data.frame(readr::read_csv("/vol/ExtraVol/Parasite_Clustered_normalized.csv"))
rownames(cnt) <- cnt$CellName
cnt <- cnt %>% dplyr::select(-CellName)
cnt <- as.data.frame(t(cnt))
```

```{r}
metadata <- as.data.frame(readr::read_csv("/vol/ExtraVol/Parasite_Clustered_Metadata.csv"))
rownames(metadata) <- metadata$CellName
metadata <- metadata %>% dplyr::select(-c(`...1`,`Unnamed: 0`, orig.ident, CellName))
```
```{r}
metadata <- metadata %>% 
  dplyr::mutate(leiden_anno_grouped = 
                  case_when(leiden_anno %in% c("0/FB_Adamdec1+_1", "2/FB_Adamdec1+_2") ~ "0-2/FB_Adamdec1+",
                          .default = leiden_anno),
                stage_grouped =
                  case_when(stage %in% c("uninfected_adult_1", "uninfected_adult_2") ~ "uninfected", 
                          .default = stage),
                condition = paste0(leiden_anno_grouped, "_", stage_grouped))
```


```{r}
seu <- CreateSeuratObject(counts = cnt, meta.data = metadata)
```

```{r}
#Convert the v5 assay to a v3 assay because LoupeR has a problem with v5 in this version.
seu[["RNA"]] <- as(object = seu[["RNA"]], Class = "Assay")
```

```{r}
seu<- SetIdent(seu, value = seu@meta.data$leiden_anno_grouped)
```

```{r}
#Check how the examples from 10X look like
clusters_example <- readRDS("/vol/ExtraVol/clusters.RDS")
projections_example <- readRDS("/vol/ExtraVol/projections.RDS")
```

```{r}
#Create the clusters and projections similar to the 10X examples
clusters <- select_clusters(seu)
projections <- list(umap = as.matrix(dplyr::select(metadata, c(UMAP_1, UMAP_2))))
```

```{r}
create_loupe(count_mat = seu@assays[["RNA"]]@counts, 
             clusters = clusters, 
             projections = projections, 
             output_name = "/vol/ExtraVol/Parasite_Loupe")
```
